config/routes.rb
Rails.application.routes.draw do
  resources :submissions, only: [:show]
  resources :text_books, only: [:show]
  devise_for :users
  root "homepage#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :submission
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :state
  has_many :subjects
  has_many :text_books, through: :subjects
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :grades
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :grade
  has_many :text_books
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :text_book
  belongs_to :user
  has_many :comments
  has_one_attached :picture
end

app/models/text_book.rb
class TextBook < ApplicationRecord
  belongs_to :subject
  has_many :submissions
  has_one_attached :cover
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :country
  belongs_to :state
  belongs_to :grade
  has_many :text_books, through: :grade
  has_many :submissions, through: :text_books

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :authenticate_user!

  def index
    @text_books = current_user.text_books
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def show
    @submission = current_user.submissions.find(params[:id])
  end
end

app/controllers/text_books_controller.rb
class TextBooksController < ApplicationController
  def show
    @text_book = current_user.text_books.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/text_books_helper.rb
module TextBooksHelper
end

app/views/homepage/index.html.erb
<% @text_books.each do |text_book| %>
    <div class="textbooks">
      <%= link_to(text_book_path(text_book)) do %>
        <h3 class="textbook-title"><%= text_book.name %></h3>
        <%= image_tag(text_book.cover) %>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Zen Homework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('/logo.png') %>
  </head>

  <body>
    <div class="header">
      <span class="logo">
        <a  href="/"><img src="/logo.png" height="100" width="100"/>ZenHomework</a>
      </span>
      <span class="profile">
        <% if user_signed_in? %>
          <span> <%= current_user.name %> </span>
        <% end %>
        </<br>>
        <span class="hmenu">
          <%= render 'devise/menu/registration_items' %>
          <%= render 'devise/menu/login_items' %>
        </span>
      </span>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p
    <%= yield %>
  </body>
</html>

app/views/submissions/show.html.erb
<h1> <%=@submission.comment%></h1>
<p><%= image_tag(@submission.picture) %></p>
<h2> Comments </h2>
<% @submission.comments.each do |comment| %>
  <p>
    <h3> <%=comment.comment%></h3>
    <h4> <%=comment.user.name%></h4>
    <span> <%=comment.created_at %></span>
  </p>
<% end %>

app/views/text_books/show.html.erb
<h1> <%=@text_book.name%></h1>
<% @text_book.submissions.each do |submission| %>
  <h2><%= link_to submission.comment, submission_path(submission)=%></h2>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users.each do |user| %>
  <%= user.username %><br/>
  <%= user.email %><br/>
  <h1><%= @user.username %></h1>
  <h5><%= @user.email%></h5>
<% end %>